# Generated by Django 5.2.1 on 2025-08-15 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvs', '0002_candidate_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='score',
            field=models.FloatField(default=0.0),
        ),
    ]
