# Generated by Django 5.2.1 on 2025-10-13 11:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvs', '0005_remove_candidate_resume_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='id',
            field=models.UUIDField(default=uuid.UUID('36beda14-db88-4d4a-a445-65ee9fec93a5'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(blank=True, default='Paris', max_length=100),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='word',
            field=models.CharField(max_length=100),
        ),
    ]
